font-blending = "linear"
theme-dark = "Glass Dark"
foreground = "#303030"
background = "#f7fbfd"
palette-0 = "#303030"
open-with-app = "Zed|dev.zed.Zed"

quit-after-last-window-closed = true

window-working-directory = "home"

default-git-client = "dev.zed.Zed"

editor-vim = true

editor-visible-whitespace = true

# unfocused-split-opacity = 0.55 (reset to default)

palette-1 = "#a31700"
palette-2 = "#0a7f3d"
palette-3 = "#af551d"
palette-4 = "#006cd8"
palette-5 = "#583cac"
palette-6 = "#00798a"
palette-7 = "#494949"
palette-8 = "#8c8c8c"
palette-9 = "#a31700"
palette-10 = "#0a7f3d"
palette-11 = "#af551d"
palette-12 = "#006cd8"
palette-13 = "#583cac"
palette-14 = "#00798a"

palette-15 = "#1c1c1c"

dock-icon-animate-progress = true

font-size = 15

window-layout = "tabs-bottom"

theme = "Glass Light"

selection-foreground = "#fafaff"
selection-background = "#ad95e9"
cursor-color = "#303030"
cursor-text = "#565656"
