#!/bin/sh
set -u

PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH:-}"
export PATH

FORCE=0
if [ "${1:-}" = "--force" ]; then
  FORCE=1
  shift
fi

OUTPUT_PATH="${1:-$HOME/.config/audio-router/config.sh}"
SWITCH_AUDIO_SOURCE="$(command -v SwitchAudioSource || true)"

if [ -z "$SWITCH_AUDIO_SOURCE" ]; then
  printf 'SwitchAudioSource is not installed.\n' >&2
  exit 127
fi

if [ -f "$OUTPUT_PATH" ] && [ "$FORCE" -ne 1 ]; then
  printf 'Keeping existing local audio router config: %s\n' "$OUTPUT_PATH"
  exit 0
fi

list_devices() {
  "$SWITCH_AUDIO_SOURCE" -a -t "$1" 2>/dev/null || true
}

current_device() {
  "$SWITCH_AUDIO_SOURCE" -c -t "$1" 2>/dev/null || true
}

first_matching_device() {
  type="$1"
  pattern="$2"

  list_devices "$type" | grep -E -m 1 "$pattern" || true
}

first_bluetooth_device() {
  pattern="$1"

  system_profiler SPBluetoothDataType 2>/dev/null | \
    sed -n "s/^[[:space:]]*\\([^:]*${pattern}[^:]*\\):$/\\1/p" | \
    head -n 1
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_assignment() {
  name="$1"
  value="$2"

  printf '%s=%s\n' "$name" "$(shell_quote "$value")"
}

mkdir -p "$(dirname "$OUTPUT_PATH")"

headphones_output="$(first_matching_device output 'AirPods')"
if [ -z "$headphones_output" ]; then
  headphones_output="$(first_bluetooth_device 'AirPods Max')"
fi
if [ -z "$headphones_output" ]; then
  headphones_output="$(current_device output)"
fi

preferred_input="$(first_matching_device input 'DJI Mic')"
if [ -z "$preferred_input" ]; then
  preferred_input="$(current_device input)"
fi

fallback_output="$(first_matching_device output 'MacBook.*(扬声器|Speakers)')"
fallback_input="$(first_matching_device input 'MacBook.*(麦克风|Microphone)|Internal Microphone')"

{
  printf '# Local audio routing preference for this Mac.\n'
  printf '# Generated by ~/dotfiles/macos/audio-router/collect-local-config.sh.\n'
  printf '# Keep this file local; device names are machine-specific.\n\n'
  write_assignment AUDIO_ROUTER_HEADPHONES_OUTPUT "$headphones_output"
  write_assignment AUDIO_ROUTER_PREFERRED_INPUT "$preferred_input"
  write_assignment AUDIO_ROUTER_FALLBACK_OUTPUT "$fallback_output"
  write_assignment AUDIO_ROUTER_FALLBACK_INPUT "$fallback_input"
  write_assignment AUDIO_ROUTER_AGENT_LABEL "local.audio-router"
  printf 'AUDIO_ROUTER_CHECK_INTERVAL_SECONDS=5\n'
} > "$OUTPUT_PATH"

printf 'Wrote local audio router config: %s\n' "$OUTPUT_PATH"
