# Taps
tap "homebrew/bundle"

# Binaries
brew "coreutils"
brew "git"
brew "git-delta"
brew "imagemagick"
brew "jq"
brew "mas"
brew "nvm"
brew "pyenv"
brew "pyenv-virtualenv"
brew "shellcheck"
brew "tldr"
brew "tree"
brew "wget"
brew "yq"

# Apps
cask "1password"
cask "alt-tab"
cask "arc"
cask "appcleaner"
cask "baidunetdisk"
cask "cheatsheet"
cask "docker"
cask "easydict"
cask "hiddenbar"
cask "iina"
cask "monitorcontrol"
cask "raycast"
cask "rewind"
cask "snipaste"
cask "telegram"
cask "the-unarchiver"
cask "visual-studio-code"
cask "warp"

# Quicklook
cask "provisionql"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookapk"
cask "webpquicklook"

# Mac App Store
mas "Ulysses", id: 1225570693
mas "微信", id: 836500024
